#!/bin/bash
#
# Notify of Homebrew updates via Notification Center on Mac OS X
#
# Based on https://github.com/rwoeber/homebrew-update-notifier

eval $(/usr/libexec/path_helper -s)

BREW=$(which brew)
[ -x ${BREW} ] || exit 1

TERMINAL_NOTIFIER=$(which terminal-notifier)
[ -x  ${TERMINAL_NOTIFIER} ] || exit 1

function outdated() {
  context=$1
  items=$2

  count=$(echo "$items" | wc -l | sed 's/^ *//')
  title="${context}: ${count} updates"

  items=$(perl -pe 's/\n/, /g' <(echo -n "${items}"))

  ${TERMINAL_NOTIFIER} ${NOTIFIER} -title "${title}" -message "${items}" -group "Homebrew-${context}"
}

${BREW} update 2>&1 > /dev/null

formula_outdated=$(${BREW} outdated --quiet)
formula_pinned=$(${BREW} list --pinned)

# Remove pinned formulae from the list of outdated formulae. See comm(1)
formula_outdated=$(comm -23 <(echo "${formula_outdated}") <(echo "${formula_pinned}"))

if [ -n "${formula_outdated}" ]; then
  outdated "Formula" "${formula_outdated}"
fi
